spring.application.name=Film_Rental_System



server.port=8082


#url
spring.datasource.url=jdbc:mysql://10.131.159.207:3306/film_rental_store
#username
spring.datasource.username=film
#password
spring.datasource.password=password
#driverclasss name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect