spring.application.name=Film_Rental_System
server.port=8082


#url
spring.datasource.url=jdbc:mysql://localhost:3306/sakila
#username
spring.datasource.username=root
#password
spring.datasource.password=Sneha@18
#driverclasss name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

#for ddl operations
spring.jpa.hibernate.ddl-auto=update
