spring.application.name=Film_Rental_System
<<<<<<< HEAD
<<<<<<< Updated upstream
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 4be3e4328dc96d87f37b6c1e28b8b4944cbf2b70
server.port= 8081

spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

#database property
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/sakila
spring.datasource.username=film
spring.datasource.password=password

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
=======
spring.datasource.url=jdbc:mysql://10.131.159.207/sakila
spring.datasource.username=film
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
=======
>>>>>>> b5d06583168d4a4cb3089be3b3b50f535f82d450
server.port=8082


#url
spring.datasource.url=jdbc:mysql://localhost:3306/sakila
#username
spring.datasource.username=root
#password
spring.datasource.password=Sneha@18
#driverclasss name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

#for ddl operations
spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
=======
server.port = 8081
>>>>>>> Stashed changes
=======
>>>>>>> a1a762af60fd220c0ec8d1b036990908225062f9
>>>>>>> 4be3e4328dc96d87f37b6c1e28b8b4944cbf2b70
>>>>>>> b5d06583168d4a4cb3089be3b3b50f535f82d450
